# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wally < Formula
  desc "Randomly change wallpaper using Unsplash Source"
  homepage "https://github.com/ltpquang/wally"
  version "1.0.0"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ltpquang/wally/releases/download/v1.0.0/wally_1.0.0_macOS_arm64.tar.gz"
      sha256 "182dea8f2f561e3c28dc91fa96b78381ab0fe86c0fb1d23b22fb45d1a99c0bdc"

      def install
        bin.install "wally"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ltpquang/wally/releases/download/v1.0.0/wally_1.0.0_macOS_x86_64.tar.gz"
      sha256 "32153b025425e162cb4b8d88a7584a570dc7bb1b3fd0954d4671e2c59cc54247"

      def install
        bin.install "wally"
      end
    end
  end
end
