# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wally < Formula
  desc "Randomly change wallpaper using Unsplash Source"
  homepage "https://github.com/ltpquang/wally"
  version "0.1.0"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ltpquang/wally/releases/download/v0.1.0/wally_0.1.0_macOS_arm64.tar.gz"
      sha256 "070352e52cec1ac51761264d6ce2ebd43293ae663cae481fa57a806c752f071e"

      def install
        bin.install "wally"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ltpquang/wally/releases/download/v0.1.0/wally_0.1.0_macOS_x86_64.tar.gz"
      sha256 "58f4085b68279b7eda8cb83978c8ea3391ab5bc8d99fc551a01a3ee0f552e805"

      def install
        bin.install "wally"
      end
    end
  end
end
